### ISSUE TITLE
Kindlegen returned error 2

### ISSUE THREAD

**Issue by dougtaylor-cb** [hakatashi/kindlegen#3]
Odd issue here.  Kindlegen works great on many of the epubs that I am trying to convert to mobi, but some of the files get a "kindlegen returned error 2" error.  The epubs of these files work fine, and I can convert them using a different converter, so I don't think the problem is with the files, unless the issue is the file size or time required to read the file.  For example, my latest test had an epub that was 403 kb convert just fine, but one that was 2500 kb received the error.

`var promises = fileObject.map(function(file){
  kindlegen(fs.readFileSync(file.filePath + file.inputFile), (error, mobi) => {
    // mobi is an instance of Buffer with the compiled mobi file 
    
    if (error){
      console.log(error);
    }
    console.log('input path: ', file.filePath);
    console.log('input file: ', file.inputFile);
    console.log('Output path: ', file.outputPath);
    console.log('Output file: ', file.outputFile);
    fs.writeFile(file.outputPath + file.outputFile, mobi, function(err){
      if (err){
        console.log(err);
      } else {
        console.log('Writing file' );
      }
    });
  });
});

Promise.all(promises).then(function(){
  console.log('writing file');
}).catch(function(err){
  console.log('err');
});`

**Comment by hakatashi** [comment]
I think this is the issue of kindlegen itself. Try converting the file with normal kindlegen way and it will display more information.

**Comment by dougtaylor-cb** [comment]
Can you explain the normal kindlegen way of converting?  I'm not sure I follow.

**Comment by hakatashi** [comment]
For instance run something like this in your shell.

```
$ node_modules/kindlegen/bin/kindlegen input.epub -c2 -verbose -o output.mobi
```

**Comment by dougtaylor-cb** [comment]
Thanks!  That's exactly what I needed.  Using that, I was able to find several different problems within the files comprising the epub (missing tags, references to non-existent html files in the toc, etc...).

It verifies that the problem isn't with kindlegen, but with the epub files themselves, and it pretty much tells me exactly what I need to do to fix them.

Thanks for all your help, and for such an awesome utility! (seriously....it really helps me manage my LN addiction )
